name: GitHub Actions Demo2
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  workflow_run:
    workflows: ["GitHub Actions Demo"]
    types:
      - completed
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: echo-test
        run: |
          echo "This is a test of the GitHub Actions workflow."
          echo "The script will not fail even if there are errors."
          echo "You can add your own commands here."
      
